### ISSUE TITLE
Code files missing

### ISSUE THREAD

**Issue by christinichka** [Carolista/LC-A5-prep-2#1]
Hi, I am a LC101 student in the independent pilot track. I forked and cloned this repo and then realized it only has a ReadMe file. Is there another way to access the html, css, and js files? I've been watching the video walk thru but it's a little blurry so I'd love to reference the code.

**Comment by Carolista** [comment]
Hi! Thanks for trying out the prep exercise! There are two other branches present, starter-code and solution, so once you switch to one of them the files should be visible in VSCode. Use the command 'git branch' in the terminal to view all available branches, then 'git checkout starter-code' to switch to the starter-code branch. 

<img width="1167" alt="Screen Shot 2021-03-31 at 8 34 45 PM" src="https://user-images.githubusercontent.com/55961845/113231351-aa809000-9260-11eb-8daa-c3ef19c07863.png">
<img width="1164" alt="Screen Shot 2021-03-31 at 8 35 22 PM" src="https://user-images.githubusercontent.com/55961845/113231354-ac4a5380-9260-11eb-9cbd-ac90d66b8ede.png">

I think you bring up a good point that students who are new to git may not immediately know to do this, so I'll update my READMEs soon.

**Comment by christinichka** [comment]
Thank you for getting back to me. I was able to get it all loaded. I really appreciate your help!
